### ISSUE TITLE
Make vs go get

### ISSUE THREAD

**Issue by teran-mckinney** [Jeffail/leaps#1]
Hi Ashley,

I'm rather new to Go so am likely missing something. Generally, I try to build a program with go get. If I go get leaps, everything builds fine enough to produce a binary to run, but there's no Javascript built. It looks like you have a minifier or something that it goes through in the end result. Ultimately, the example comes up without a leaps.js file, while the rest seem to be there. The README also references port 8080, which no longer seems to be the example default in the current codebase.

I see that you encourage make use instead. Why do you have a Makefile? Would it be possible to put the needed functionality in however Go usually does builds? It seems like Go uses some kind of Godeps/Procfile, but I really ought to look up on that to say for sure.

Running the make, it looks like I need vet, which is in Go. I installed it and ran it. jshint I'm not so sure on, where is it from?

If you are curious, I am running FreeBSD and can confirm that the webserver seems to act as expected.

Thank you!

Sincerely,
Teran

**Comment by Jeffail** [comment]
Hey Teran,

Firstly, thanks for the feedback, I'm about to push an update to both the README and Makefile that hopefully answers some of these questions. I'll probably revise those changes tomorrow after some sleep :sleepy:

The Makefile is there because I initially assumed the standard go build tools wouldn't easily support adding steps such as linting and minifying JavaScript. That might not actually be the case anymore, and if so then I'd happily switch providing it becomes simpler than my dubious Makefile. It's on my TODO list to take another look at the build system, it'd certainly be great to have `go get` manage everything.

To get the dependencies for building/testing/linting JavaScript you need to have node.js (and npm) installed and then do `sudo npm install -g uglifyjs jshint nodeunit`, those are node.js utilities for minifying, linting, and unit testing the JavaScript libraries.

Alternatively, if you're only interested in the service side of things but want the client libraries to play with then you can just grab a .tar.gz from https://github.com/Jeffail/leaps/releases which will have them ready to use.

Cheers!

Ash
