### ISSUE TITLE
Modification of leap.js to fit into Ace Editor 1.2.2

### ISSUE THREAD

**Issue by manchunw** [Jeffail/leaps#16]
I want to integrate the latest version of Ace editor (1.2.2) into Leaps when I realize that the API of Ace has changed, not the same API in Ace version 1.1.8 when Leaps was designed. I have modified the code in `leaps.js` to fit the latest Ace.

No harm to share it here. Hope that others can find this useful.

Line 983, leaps.js

``` javascript
    switch (e.action) {
    case "insert":
        tform.position = live_document.positionToIndex(e.start, 0);
        tform.insert = e.lines.join(nl);
        break;
    case "remove":
        tform.position = live_document.positionToIndex(e.start, 0);
        tform.num_delete = e.lines.join(nl).length;
        break;
      }
```

**Comment by Jeffail** [comment]
Hey @manchunw,

Thanks! This is great. I might as well add this into master at some point.

**Comment by joeblew99** [comment]
Has this been added in the master tag ?

**Comment by Jeffail** [comment]
Hey @joeblew99, I switched to the latest ACE with these changes a while ago and forgot to comment here. Sorry!

However, since then I've also had to move to CodeMirror as ACE cannot handle UTF-16 surrogate pairs, but the code for an ACE 1.2.2+ editor with leaps can still be found at https://github.com/Jeffail/leaps/tree/master/cmd/leaps/www-ace, if you intend to use it with the latest leaps service it'll need a few minor tweaks though.
