### ISSUE TITLE
save button

### ISSUE THREAD

**Issue by kybin** [Jeffail/leaps#36]
Hi, thank you for your work, Jeffail.

It would be better if we have save button.

It feels little bit unsafe, because every changes are applied to file directly.

**Comment by Jeffail** [comment]
Hey @kybin, sounds reasonable. I'll take a look at this next time I'm working on the UI.

**Comment by qknight** [comment]
@kybin you don't want a save button but rather a 'sync' indicator like a short text saying "saved" or a icon which indicates sync

**Comment by kybin** [comment]
Hi, @qknight .

I think that only safe when we have automatic versioned backup.
Is it currently supported?

**Comment by Jeffail** [comment]
Hey both, I've been thinking about this a lot. I think I want to change the current behaviour so that leaps won't write over your files by default. Right now it seems like a trap for new users who might not realise their files will be overwritten, but I also want to keep it simple and easy for users who want it.

My thoughts are that a 'save' button wouldn't really fit as a solution, because unless I implement real authenticated user accounts into leaps it means anyone on that web page can still ruin your files without your permission or knowledge.

I would like to instead have leaps generate a patch file as your work continues, that is constantly updating, and if applied to the directory leaps is running in will apply all the changes you made as a manual last step after closing leaps. This allows you to review the changes before they are committed, and the commit step should be a simple command such as `leaps commit`.

The benefit of the above option is that it protects new users, or users who aren't using a version control system. I can also add a flag to leaps (something like `-w`) which would change the behaviour to what it currently does, which means power users can skip the commit step at the end.

Do you think something like that would help?

**Comment by Jeffail** [comment]
Leaps --safe and --commit flags have been in for a while now, and while dog-fooding I'm enjoying the flow. I'm closing this issue but feel free to reopen if you have any new thoughts.
